bar:
  height: 16
  location: bottom
  layer: top
  background: 35353500
  foreground: 353535ff
  margin: 0
  spacing: 0
  font: Source Code Pro:pixelsize=14:style=bold, Font Awesome 6 Free:pixelsize=13:style=solid

  right:
    - label:
        content:
          - string:
              text: ""
              foreground: 00eff3ff
    - clock:
       content:
          - string:
              text: "{time}"
              margin: 9
              foreground: 353535ff
              deco:
                background:
                  color: 00eff3ff
    - label:
        content:
          - string:
              text: ""
              foreground: 00afffff
              deco:
                background:
                  color: 00eff3ff

    - clock:
        date-format: "%a%d" 
        content:
          - string:
              text: "{date}"
              margin: 9
              deco:
                background:
                  color: 00afffff
    - label:
        content:
          - string:
              text: ""
              foreground: 097cb0ff
              deco:
                background:
                  color: 00afffff
    - clock:
        date-format: "%b" 
        content:
          - string:
              text: "{date}"
              margin: 9
              deco:
                background:
                  color: 097cb0ff

  left:
    - network:
        poll-interval: 500
        content:
          map:
            conditions:
              state == up:
              - string:
                  text: ""
                  margin: 9
                  foreground: e6e6e6ff
                  deco:
                    background:
                      color: 097cb0ff
              state == down:
              - string:
                  text: "⚠ DOWN"
                  foreground: d64922ff
                  margin: 9
                  deco:
                    background:
                      color: 097cb0ff
    - label:
        content:
          - string:
              text: ""
              foreground: 097cb0ff
              deco:
                background:
                  color: 00afffff

    - cpu:
        poll-interval: 500
        content:
          map:
            conditions:
              id < 0:
                - string:
                    text: " {cpu}%"
                    margin: 9
                    deco:
                      background:
                        color: 00afffff
    - label:
        content:
          - string:
              text: ""
              foreground: 00afffff
              deco:
                background:
                  color: 00eff3ff
    - mem:
        poll-interval: 500
        content:
        - string:
            text: " {free:mb}"
            margin: 9
            deco:
              background:
                    color: 00eff3ff
    - label:
        content:
          - string:
              text: ""
              foreground: 00eff3ff

